### ISSUE TITLE
/v1/bootstrap/libraries/css/font-awesome.css returns 500

### ISSUE THREAD

**Issue by UnbounDev** [jsdelivr/api#59]
Never mind that the request URL is inappropriately formatted, the response is an express stacktrace:

```
500 TypeError: Cannot call method 'filter' of undefined
at /mnt/var/vcap.local/dea/apps/jsdelivr-api2-0-a7be40c35b43d413fa1b2cafd41dffc8/app/api.js:54:40
at /mnt/var/vcap.local/dea/apps/jsdelivr-api2-0-a7be40c35b43d413fa1b2cafd41dffc8/app/node_modules/object-sugar/lib/utils/operate.js:16:24
at /mnt/var/vcap.local/dea/apps/jsdelivr-api2-0-a7be40c35b43d413fa1b2cafd41dffc8/app/node_modules/object-sugar/lib/get_one.js:11:16
at /mnt/var/vcap.local/dea/apps/jsdelivr-api2-0-a7be40c35b43d413fa1b2cafd41dffc8/app/node_modules/object-sugar/lib/get_all.js:49:5
at getOne (/mnt/var/vcap.local/dea/apps/jsdelivr-api2-0-a7be40c35b43d413fa1b2cafd41dffc8/app/node_modules/object-sugar/lib/get_one.js:6:5)
at Object.getOne (/mnt/var/vcap.local/dea/apps/jsdelivr-api2-0-a7be40c35b43d413fa1b2cafd41dffc8/app/node_modules/object-sugar/lib/utils/operate.js:27:16)
at /mnt/var/vcap.local/dea/apps/jsdelivr-api2-0-a7be40c35b43d413fa1b2cafd41dffc8/app/api.js:47:19
at callbacks (/mnt/var/vcap.local/dea/apps/jsdelivr-api2-0-a7be40c35b43d413fa1b2cafd41dffc8/app/node_modules/express/lib/router/index.js:164:37)
at param (/mnt/var/vcap.local/dea/apps/jsdelivr-api2-0-a7be40c35b43d413fa1b2cafd41dffc8/app/node_modules/express/lib/router/index.js:138:11)
at param (/mnt/var/vcap.local/dea/apps/jsdelivr-api2-0-a7be40c35b43d413fa1b2cafd41dffc8/app/node_modules/express/lib/router/index.js:135:11)
```

The response ought to cleanly resolve the error and return a helpful message to the caller.

**Comment by UnbounDev** [comment]
Fixed as of PR #63
